// <auto-generated />
using System;
using Biblioteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20250920225043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("042eda71-25ab-48e3-9667-eaf0ef25cbee"),
                            Author = "Fyodor Dostoyevski",
                            CoverImage = "covers/sucveceza.jpg",
                            Genre = "Roman",
                            Publisher = "İletişim Yayınları",
                            Summary = "Raskolnikov’un vicdan azabı ve suç psikolojisini konu alan klasik.",
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = new Guid("f7496ed5-606d-4494-9ddb-0e24b979fca8"),
                            Author = "George Orwell",
                            CoverImage = "covers/1984.jpg",
                            Genre = "Distopya",
                            Publisher = "Can Yayınları",
                            Summary = "Totaliter rejimlerin tehlikelerini anlatan klasik eser.",
                            Title = "1984"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
