// <auto-generated />
using System;
using Biblioteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20250921154225_AddNotesFieldsToBook")]
    partial class AddNotesFieldsToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteQuote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f76010b-51d7-4549-9c8f-c591419cea4b"),
                            Author = "Fyodor Dostoevsky",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Classic Novel",
                            Notes = "",
                            Publisher = "Penguin Classics",
                            Rating = 0,
                            Summary = "The story of Raskolnikov, a young man tormented by guilt after committing a murder.",
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("c7ab4a1e-d8fa-46d5-8932-d67bfd69acc9"),
                            Author = "George Orwell",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Dystopian",
                            Notes = "",
                            Publisher = "Secker & Warburg",
                            Rating = 0,
                            Summary = "A chilling portrayal of a totalitarian regime and the dangers of absolute power.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("de170267-eacf-401f-84d8-43f3b31260f8"),
                            Author = "Sabahattin Ali",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Romance",
                            Notes = "",
                            Publisher = "Penguin Modern Classics",
                            Rating = 0,
                            Summary = "The unforgettable love story of Raif Efendi and Maria Puder.",
                            Title = "Madonna in a Fur Coat"
                        },
                        new
                        {
                            Id = new Guid("abf1ef9e-ffee-481e-bf40-ca6d2a233107"),
                            Author = "Victor Hugo",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Classic Novel",
                            Notes = "",
                            Publisher = "Random House",
                            Rating = 0,
                            Summary = "The epic story of Jean Valjean’s struggle for redemption in 19th-century France.",
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = new Guid("ab5c66d8-4cae-49f6-ba9b-468dbe0c3089"),
                            Author = "Antoine de Saint-Exupéry",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Children / Philosophy",
                            Notes = "",
                            Publisher = "Reynal & Hitchcock",
                            Rating = 0,
                            Summary = "A poetic tale about love, friendship, and the meaning of life.",
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = new Guid("d775be5a-22b6-44ba-bc00-0ee35ccb427b"),
                            Author = "Oğuz Atay",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Modern Literature",
                            Notes = "",
                            Publisher = "Everest Publishing",
                            Rating = 0,
                            Summary = "A cornerstone of modern Turkish literature, exploring alienation and identity.",
                            Title = "The Disconnected"
                        },
                        new
                        {
                            Id = new Guid("5b7b5fdc-80bd-416a-8e9f-5be8a55777f2"),
                            Author = "Orhan Pamuk",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Historical Novel",
                            Notes = "",
                            Publisher = "Knopf",
                            Rating = 0,
                            Summary = "A rich tale set in the Ottoman Empire, blending art, religion, and mystery.",
                            Title = "My Name is Red"
                        },
                        new
                        {
                            Id = new Guid("f6f120a5-2cb1-4afb-9204-420ef8547ad8"),
                            Author = "Zülfü Livaneli",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Historical Fiction",
                            Notes = "",
                            Publisher = "Other Press",
                            Rating = 0,
                            Summary = "A novel intertwining love, tragedy, and history across generations.",
                            Title = "Serenade"
                        },
                        new
                        {
                            Id = new Guid("90c4e8cb-7698-49a3-9794-cca8a59cbaa0"),
                            Author = "Taylor Jenkins Reid",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Historical Fiction",
                            Notes = "",
                            Publisher = "Atria Books",
                            Rating = 0,
                            Summary = "An aging Hollywood icon tells the story of her scandalous life and seven marriages.",
                            Title = "The Seven Husbands of Evelyn Hugo"
                        },
                        new
                        {
                            Id = new Guid("15e64535-6436-432b-ada5-4a3076e3e11c"),
                            Author = "Harper Lee",
                            CoverImage = "",
                            FavoriteQuote = "",
                            Genre = "Classic",
                            Notes = "",
                            Publisher = "J.B. Lippincott & Co.",
                            Rating = 0,
                            Summary = "A timeless novel about racial injustice and childhood in the Deep South.",
                            Title = "To Kill a Mockingbird"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
