// <auto-generated />
using System;
using Biblioteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20250921115650_AddGenreToBooks")]
    partial class AddGenreToBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("27b8af4f-9ac0-4ab2-9f56-bf988fc39190"),
                            Author = "Fyodor Dostoevsky",
                            CoverImage = "",
                            Genre = "Classic Novel",
                            Publisher = "Penguin Classics",
                            Summary = "The story of Raskolnikov, a young man tormented by guilt after committing a murder.",
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("7d26be01-7084-43e9-ae70-96d0c033a54f"),
                            Author = "George Orwell",
                            CoverImage = "",
                            Genre = "Dystopian",
                            Publisher = "Secker & Warburg",
                            Summary = "A chilling portrayal of a totalitarian regime and the dangers of absolute power.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("aac49d5c-22e2-4acc-90f3-76b33485f29a"),
                            Author = "Sabahattin Ali",
                            CoverImage = "",
                            Genre = "Romance",
                            Publisher = "Penguin Modern Classics",
                            Summary = "The unforgettable love story of Raif Efendi and Maria Puder.",
                            Title = "Madonna in a Fur Coat"
                        },
                        new
                        {
                            Id = new Guid("e230d0e9-61a7-436b-85ad-5f0537708e88"),
                            Author = "Victor Hugo",
                            CoverImage = "",
                            Genre = "Classic Novel",
                            Publisher = "Random House",
                            Summary = "The epic story of Jean Valjean’s struggle for redemption in 19th-century France.",
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = new Guid("a48769a7-722b-4615-8c72-a054fd59978b"),
                            Author = "Antoine de Saint-Exupéry",
                            CoverImage = "",
                            Genre = "Children / Philosophy",
                            Publisher = "Reynal & Hitchcock",
                            Summary = "A poetic tale about love, friendship, and the meaning of life.",
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = new Guid("8fd9b7a4-ba65-4db4-ad17-abb28d1b0228"),
                            Author = "Oğuz Atay",
                            CoverImage = "",
                            Genre = "Modern Literature",
                            Publisher = "Everest Publishing",
                            Summary = "A cornerstone of modern Turkish literature, exploring alienation and identity.",
                            Title = "The Disconnected"
                        },
                        new
                        {
                            Id = new Guid("24853c47-cca4-4785-b926-bb8a48ebc9aa"),
                            Author = "Orhan Pamuk",
                            CoverImage = "",
                            Genre = "Historical Novel",
                            Publisher = "Knopf",
                            Summary = "A rich tale set in the Ottoman Empire, blending art, religion, and mystery.",
                            Title = "My Name is Red"
                        },
                        new
                        {
                            Id = new Guid("81a84453-f140-44bf-ac5e-fe139910ecca"),
                            Author = "Zülfü Livaneli",
                            CoverImage = "",
                            Genre = "Historical Fiction",
                            Publisher = "Other Press",
                            Summary = "A novel intertwining love, tragedy, and history across generations.",
                            Title = "Serenade"
                        },
                        new
                        {
                            Id = new Guid("d361976c-b0b2-4f29-b5a1-dab4c9403493"),
                            Author = "Taylor Jenkins Reid",
                            CoverImage = "",
                            Genre = "Historical Fiction",
                            Publisher = "Atria Books",
                            Summary = "An aging Hollywood icon tells the story of her scandalous life and seven marriages.",
                            Title = "The Seven Husbands of Evelyn Hugo"
                        },
                        new
                        {
                            Id = new Guid("f398baf1-26a7-4550-9d3a-4e455eee178a"),
                            Author = "Harper Lee",
                            CoverImage = "",
                            Genre = "Classic",
                            Publisher = "J.B. Lippincott & Co.",
                            Summary = "A timeless novel about racial injustice and childhood in the Deep South.",
                            Title = "To Kill a Mockingbird"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
