// <auto-generated />
using System;
using Biblioteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20250920233548_SeedEnglishBooks")]
    partial class SeedEnglishBooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d927fda-89ac-4ad4-ad3d-4e65b7833b67"),
                            Author = "Fyodor Dostoevsky",
                            CoverImage = "",
                            Genre = "Classic Novel",
                            Publisher = "Penguin Classics",
                            Summary = "The story of Raskolnikov, a young man tormented by guilt after committing a murder.",
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = new Guid("37428ad1-2d05-467f-a038-636679e23394"),
                            Author = "George Orwell",
                            CoverImage = "",
                            Genre = "Dystopian",
                            Publisher = "Secker & Warburg",
                            Summary = "A chilling portrayal of a totalitarian regime and the dangers of absolute power.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("b7a81886-2055-43e7-8475-a44772a6ebbc"),
                            Author = "Sabahattin Ali",
                            CoverImage = "",
                            Genre = "Romance",
                            Publisher = "Penguin Modern Classics",
                            Summary = "The unforgettable love story of Raif Efendi and Maria Puder.",
                            Title = "Madonna in a Fur Coat"
                        },
                        new
                        {
                            Id = new Guid("debff881-f93c-4d51-ac6c-dad48fa4231d"),
                            Author = "Victor Hugo",
                            CoverImage = "",
                            Genre = "Classic Novel",
                            Publisher = "Random House",
                            Summary = "The epic story of Jean Valjean’s struggle for redemption in 19th-century France.",
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = new Guid("709ed0eb-5143-434b-8a73-e7bf72bda2d8"),
                            Author = "Antoine de Saint-Exupéry",
                            CoverImage = "",
                            Genre = "Children / Philosophy",
                            Publisher = "Reynal & Hitchcock",
                            Summary = "A poetic tale about love, friendship, and the meaning of life.",
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = new Guid("94317ded-7cad-4f73-aacf-541960a9a375"),
                            Author = "Oğuz Atay",
                            CoverImage = "",
                            Genre = "Modern Literature",
                            Publisher = "Everest Publishing",
                            Summary = "A cornerstone of modern Turkish literature, exploring alienation and identity.",
                            Title = "The Disconnected"
                        },
                        new
                        {
                            Id = new Guid("d49d0dbb-074d-49cd-8968-3647a38b1013"),
                            Author = "Orhan Pamuk",
                            CoverImage = "",
                            Genre = "Historical Novel",
                            Publisher = "Knopf",
                            Summary = "A rich tale set in the Ottoman Empire, blending art, religion, and mystery.",
                            Title = "My Name is Red"
                        },
                        new
                        {
                            Id = new Guid("7483ea7a-9bba-484b-a893-b6067058fb57"),
                            Author = "Zülfü Livaneli",
                            CoverImage = "",
                            Genre = "Historical Fiction",
                            Publisher = "Other Press",
                            Summary = "A novel intertwining love, tragedy, and history across generations.",
                            Title = "Serenade"
                        },
                        new
                        {
                            Id = new Guid("c2a2fae5-28e1-4521-97e8-85c5bc416460"),
                            Author = "Taylor Jenkins Reid",
                            CoverImage = "",
                            Genre = "Historical Fiction",
                            Publisher = "Atria Books",
                            Summary = "An aging Hollywood icon tells the story of her scandalous life and seven marriages.",
                            Title = "The Seven Husbands of Evelyn Hugo"
                        },
                        new
                        {
                            Id = new Guid("873e2667-9efe-4c02-bee1-4143181f1fc8"),
                            Author = "Harper Lee",
                            CoverImage = "",
                            Genre = "Classic",
                            Publisher = "J.B. Lippincott & Co.",
                            Summary = "A timeless novel about racial injustice and childhood in the Deep South.",
                            Title = "To Kill a Mockingbird"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
